/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (C) 2026 Interpretica Unipessoal Lda */
/** @file
 * @brief The embedded tsf-ai python helper (GENERATED from
 *        tapi_ai_helper.py.in - edit the .py.in and regenerate). */
#include "tapi_ai_internal.h"

/* See description in tapi_ai_internal.h */
const char tapi_ai_helper_py[] =
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# Copyright (C) 2026 Interpretica Unipessoal Lda\n"
    "#\n"
    "# The tsf-ai helper: one provider-neutral request spec in on stdin, a\n"
    "# stream of line events out on stdout. Standard library only (urllib,\n"
    "# json, base64, ssl) so it runs on any agent that has python3. The API\n"
    "# key is read from the environment (TSF_AI_KEY), never from argv.\n"
    "#\n"
    "# Input (stdin): one JSON object\n"
    "#   {shape, base_url, model, system, messages:[{role,text,attachments:\n"
    "#    [{path,media_type}]}], max_tokens, temperature, json_mode, stream}\n"
    "# Output (stdout): one JSON object per line\n"
    "#   {\"t\":\"delta\",\"text\":\"...\"}                      (streaming pieces)\n"
    "#   {\"t\":\"final\",\"text\":..,\"model\":..,\"finish_reason\":..,\"usage\":{...}}\n"
    "#   {\"t\":\"error\",\"message\":\"...\",\"status\":N}\n"
    "import base64\n"
    "import json\n"
    "import os\n"
    "import ssl\n"
    "import sys\n"
    "import urllib.error\n"
    "import urllib.request\n"
    "\n"
    "\n"
    "def emit(obj):\n"
    "    # Compact separators (no spaces): the C side searches for literal\n"
    "    # \"t\":\"final\" etc, so the event lines must not carry \"t\": \"final\".\n"
    "    sys.stdout.write(json.dumps(obj, separators=(\",\", \":\")) + \"\\n\")\n"
    "    sys.stdout.flush()\n"
    "\n"
    "\n"
    "def die(message, status=0):\n"
    "    emit({\"t\": \"error\", \"message\": str(message), \"status\": status})\n"
    "    sys.exit(0)\n"
    "\n"
    "\n"
    "def file_b64(path):\n"
    "    with open(path, \"rb\") as f:\n"
    "        return base64.b64encode(f.read()).decode(\"ascii\")\n"
    "\n"
    "\n"
    "def build_openai(spec):\n"
    "    msgs = []\n"
    "    if spec.get(\"system\"):\n"
    "        msgs.append({\"role\": \"system\", \"content\": spec[\"system\"]})\n"
    "    for m in spec[\"messages\"]:\n"
    "        atts = m.get(\"attachments\") or []\n"
    "        if not atts:\n"
    "            msgs.append({\"role\": m[\"role\"], \"content\": m[\"text\"]})\n"
    "            continue\n"
    "        parts = [{\"type\": \"text\", \"text\": m[\"text\"]}]\n"
    "        for a in atts:\n"
    "            mt = a[\"media_type\"]\n"
    "            data = file_b64(a[\"path\"])\n"
    "            if mt.startswith(\"image/\"):\n"
    "                parts.append({\"type\": \"image_url\",\n"
    "                              \"image_url\":\n"
    "                                  {\"url\": \"data:%s;base64,%s\" % (mt, data)}})\n"
    "            else:\n"
    "                # OpenAI chat takes documents as file parts (base64 data).\n"
    "                parts.append({\"type\": \"file\",\n"
    "                              \"file\": {\"filename\": os.path.basename(a[\"path\"]),\n"
    "                                       \"file_data\":\n"
    "                                           \"data:%s;base64,%s\" % (mt, data)}})\n"
    "        msgs.append({\"role\": m[\"role\"], \"content\": parts})\n"
    "    body = {\"model\": spec[\"model\"], \"messages\": msgs}\n"
    "    if spec.get(\"max_tokens\"):\n"
    "        body[\"max_tokens\"] = spec[\"max_tokens\"]\n"
    "    if spec.get(\"temperature\") is not None:\n"
    "        body[\"temperature\"] = spec[\"temperature\"]\n"
    "    if spec.get(\"json_mode\"):\n"
    "        body[\"response_format\"] = {\"type\": \"json_object\"}\n"
    "    if spec.get(\"stream\"):\n"
    "        body[\"stream\"] = True\n"
    "        body[\"stream_options\"] = {\"include_usage\": True}\n"
    "    url = spec[\"base_url\"].rstrip(\"/\") + \"/chat/completions\"\n"
    "    headers = {\"Content-Type\": \"application/json\"}\n"
    "    key = os.environ.get(\"TSF_AI_KEY\")\n"
    "    if key:\n"
    "        headers[\"Authorization\"] = \"Bearer \" + key\n"
    "    return url, headers, body\n"
    "\n"
    "\n"
    "def build_anthropic(spec):\n"
    "    msgs = []\n"
    "    for m in spec[\"messages\"]:\n"
    "        blocks = []\n"
    "        for a in m.get(\"attachments\") or []:\n"
    "            mt = a[\"media_type\"]\n"
    "            src = {\"type\": \"base64\", \"media_type\": mt, \"data\": file_b64(a[\"path\"])}\n"
    "            if mt == \"application/pdf\":\n"
    "                blocks.append({\"type\": \"document\", \"source\": src})\n"
    "            else:\n"
    "                blocks.append({\"type\": \"image\", \"source\": src})\n"
    "        if m[\"text\"]:\n"
    "            blocks.append({\"type\": \"text\", \"text\": m[\"text\"]})\n"
    "        msgs.append({\"role\": m[\"role\"], \"content\": blocks})\n"
    "    body = {\"model\": spec[\"model\"], \"messages\": msgs,\n"
    "            \"max_tokens\": spec.get(\"max_tokens\") or 1024}\n"
    "    if spec.get(\"system\"):\n"
    "        body[\"system\"] = spec[\"system\"]\n"
    "    if spec.get(\"temperature\") is not None:\n"
    "        body[\"temperature\"] = spec[\"temperature\"]\n"
    "    if spec.get(\"stream\"):\n"
    "        body[\"stream\"] = True\n"
    "    url = spec[\"base_url\"].rstrip(\"/\") + \"/v1/messages\"\n"
    "    headers = {\"Content-Type\": \"application/json\",\n"
    "               \"anthropic-version\": \"2023-06-01\"}\n"
    "    key = os.environ.get(\"TSF_AI_KEY\")\n"
    "    if key:\n"
    "        headers[\"x-api-key\"] = key\n"
    "    return url, headers, body\n"
    "\n"
    "\n"
    "def build_gemini(spec):\n"
    "    contents = []\n"
    "    for m in spec[\"messages\"]:\n"
    "        role = \"model\" if m[\"role\"] == \"assistant\" else \"user\"\n"
    "        parts = []\n"
    "        if m[\"text\"]:\n"
    "            parts.append({\"text\": m[\"text\"]})\n"
    "        for a in m.get(\"attachments\") or []:\n"
    "            parts.append({\"inline_data\": {\"mime_type\": a[\"media_type\"],\n"
    "                                          \"data\": file_b64(a[\"path\"])}})\n"
    "        contents.append({\"role\": role, \"parts\": parts})\n"
    "    body = {\"contents\": contents}\n"
    "    gen = {}\n"
    "    if spec.get(\"max_tokens\"):\n"
    "        gen[\"maxOutputTokens\"] = spec[\"max_tokens\"]\n"
    "    if spec.get(\"temperature\") is not None:\n"
    "        gen[\"temperature\"] = spec[\"temperature\"]\n"
    "    if spec.get(\"json_mode\"):\n"
    "        gen[\"responseMimeType\"] = \"application/json\"\n"
    "    if gen:\n"
    "        body[\"generationConfig\"] = gen\n"
    "    if spec.get(\"system\"):\n"
    "        body[\"systemInstruction\"] = {\"parts\": [{\"text\": spec[\"system\"]}]}\n"
    "    verb = \"streamGenerateContent\" if spec.get(\"stream\") else \"generateContent\"\n"
    "    url = \"%s/models/%s:%s\" % (spec[\"base_url\"].rstrip(\"/\"), spec[\"model\"], verb)\n"
    "    if spec.get(\"stream\"):\n"
    "        url += \"?alt=sse\"\n"
    "    headers = {\"Content-Type\": \"application/json\"}\n"
    "    key = os.environ.get(\"TSF_AI_KEY\")\n"
    "    if key:\n"
    "        headers[\"x-goog-api-key\"] = key\n"
    "    return url, headers, body\n"
    "\n"
    "\n"
    "BUILDERS = {\"openai\": build_openai, \"anthropic\": build_anthropic,\n"
    "            \"gemini\": build_gemini}\n"
    "\n"
    "\n"
    "def open_request(url, headers, body):\n"
    "    data = json.dumps(body).encode(\"utf-8\")\n"
    "    req = urllib.request.Request(url, data=data, headers=headers, method=\"POST\")\n"
    "    ctx = ssl.create_default_context()\n"
    "    if os.environ.get(\"TSF_AI_INSECURE\") == \"1\":\n"
    "        ctx.check_hostname = False\n"
    "        ctx.verify_mode = ssl.CERT_NONE\n"
    "    return urllib.request.urlopen(req, timeout=float(\n"
    "        os.environ.get(\"TSF_AI_HTTP_TIMEOUT\", \"120\")), context=ctx)\n"
    "\n"
    "\n"
    "# --- non-streaming response readers -------------------------------------\n"
    "\n"
    "def read_openai(obj):\n"
    "    ch = (obj.get(\"choices\") or [{}])[0]\n"
    "    text = (ch.get(\"message\") or {}).get(\"content\") or \"\"\n"
    "    if isinstance(text, list):\n"
    "        text = \"\".join(p.get(\"text\", \"\") for p in text if isinstance(p, dict))\n"
    "    u = obj.get(\"usage\") or {}\n"
    "    return {\"text\": text, \"model\": obj.get(\"model\"),\n"
    "            \"finish_reason\": ch.get(\"finish_reason\"),\n"
    "            \"usage\": {\"input\": u.get(\"prompt_tokens\"),\n"
    "                      \"output\": u.get(\"completion_tokens\"),\n"
    "                      \"total\": u.get(\"total_tokens\")}}\n"
    "\n"
    "\n"
    "def read_anthropic(obj):\n"
    "    text = \"\".join(b.get(\"text\", \"\") for b in obj.get(\"content\") or []\n"
    "                   if b.get(\"type\") == \"text\")\n"
    "    u = obj.get(\"usage\") or {}\n"
    "    i, o = u.get(\"input_tokens\"), u.get(\"output_tokens\")\n"
    "    return {\"text\": text, \"model\": obj.get(\"model\"),\n"
    "            \"finish_reason\": obj.get(\"stop_reason\"),\n"
    "            \"usage\": {\"input\": i, \"output\": o,\n"
    "                      \"total\": (i + o) if i is not None and o is not None\n"
    "                      else None}}\n"
    "\n"
    "\n"
    "def read_gemini(obj):\n"
    "    cand = (obj.get(\"candidates\") or [{}])[0]\n"
    "    parts = (cand.get(\"content\") or {}).get(\"parts\") or []\n"
    "    text = \"\".join(p.get(\"text\", \"\") for p in parts if \"text\" in p)\n"
    "    u = obj.get(\"usageMetadata\") or {}\n"
    "    return {\"text\": text, \"model\": obj.get(\"modelVersion\"),\n"
    "            \"finish_reason\": cand.get(\"finishReason\"),\n"
    "            \"usage\": {\"input\": u.get(\"promptTokenCount\"),\n"
    "                      \"output\": u.get(\"candidatesTokenCount\"),\n"
    "                      \"total\": u.get(\"totalTokenCount\")}}\n"
    "\n"
    "\n"
    "READERS = {\"openai\": read_openai, \"anthropic\": read_anthropic,\n"
    "           \"gemini\": read_gemini}\n"
    "\n"
    "\n"
    "# --- streaming delta extractors (per SSE data object) -------------------\n"
    "\n"
    "def delta_openai(obj, state):\n"
    "    ch = (obj.get(\"choices\") or [{}])\n"
    "    piece = \"\"\n"
    "    if ch:\n"
    "        piece = ((ch[0].get(\"delta\") or {}).get(\"content\")) or \"\"\n"
    "        if ch[0].get(\"finish_reason\"):\n"
    "            state[\"finish_reason\"] = ch[0][\"finish_reason\"]\n"
    "    if obj.get(\"usage\"):\n"
    "        u = obj[\"usage\"]\n"
    "        state[\"usage\"] = {\"input\": u.get(\"prompt_tokens\"),\n"
    "                          \"output\": u.get(\"completion_tokens\"),\n"
    "                          \"total\": u.get(\"total_tokens\")}\n"
    "    if obj.get(\"model\"):\n"
    "        state[\"model\"] = obj[\"model\"]\n"
    "    return piece\n"
    "\n"
    "\n"
    "def delta_anthropic(obj, state):\n"
    "    t = obj.get(\"type\")\n"
    "    if t == \"message_start\":\n"
    "        u = (obj.get(\"message\") or {}).get(\"usage\") or {}\n"
    "        state.setdefault(\"usage\", {})[\"input\"] = u.get(\"input_tokens\")\n"
    "        state[\"model\"] = (obj.get(\"message\") or {}).get(\"model\")\n"
    "    elif t == \"content_block_delta\":\n"
    "        return (obj.get(\"delta\") or {}).get(\"text\") or \"\"\n"
    "    elif t == \"message_delta\":\n"
    "        u = obj.get(\"usage\") or {}\n"
    "        if u.get(\"output_tokens\") is not None:\n"
    "            state.setdefault(\"usage\", {})[\"output\"] = u[\"output_tokens\"]\n"
    "        d = obj.get(\"delta\") or {}\n"
    "        if d.get(\"stop_reason\"):\n"
    "            state[\"finish_reason\"] = d[\"stop_reason\"]\n"
    "    return \"\"\n"
    "\n"
    "\n"
    "def delta_gemini(obj, state):\n"
    "    cand = (obj.get(\"candidates\") or [{}])[0]\n"
    "    parts = (cand.get(\"content\") or {}).get(\"parts\") or []\n"
    "    if cand.get(\"finishReason\"):\n"
    "        state[\"finish_reason\"] = cand[\"finishReason\"]\n"
    "    u = obj.get(\"usageMetadata\")\n"
    "    if u:\n"
    "        state[\"usage\"] = {\"input\": u.get(\"promptTokenCount\"),\n"
    "                          \"output\": u.get(\"candidatesTokenCount\"),\n"
    "                          \"total\": u.get(\"totalTokenCount\")}\n"
    "    return \"\".join(p.get(\"text\", \"\") for p in parts if \"text\" in p)\n"
    "\n"
    "\n"
    "DELTAS = {\"openai\": delta_openai, \"anthropic\": delta_anthropic,\n"
    "          \"gemini\": delta_gemini}\n"
    "\n"
    "\n"
    "def run_stream(shape, resp):\n"
    "    state = {\"model\": None, \"finish_reason\": None, \"usage\": {}}\n"
    "    delta = DELTAS[shape]\n"
    "    for raw in resp:\n"
    "        line = raw.decode(\"utf-8\", \"replace\").rstrip(\"\\r\\n\")\n"
    "        if not line or not line.startswith(\"data:\"):\n"
    "            continue\n"
    "        payload = line[5:].strip()\n"
    "        if payload == \"[DONE]\":\n"
    "            break\n"
    "        try:\n"
    "            obj = json.loads(payload)\n"
    "        except ValueError:\n"
    "            continue\n"
    "        piece = delta(obj, state)\n"
    "        if piece:\n"
    "            emit({\"t\": \"delta\", \"text\": piece})\n"
    "    u = state.get(\"usage\") or {}\n"
    "    if u.get(\"total\") is None and u.get(\"input\") is not None \\\n"
    "            and u.get(\"output\") is not None:\n"
    "        u[\"total\"] = u[\"input\"] + u[\"output\"]\n"
    "    emit({\"t\": \"final\", \"text\": \"\", \"model\": state.get(\"model\"),\n"
    "          \"finish_reason\": state.get(\"finish_reason\"), \"usage\": u})\n"
    "\n"
    "\n"
    "def main():\n"
    "    try:\n"
    "        spec = json.load(sys.stdin)\n"
    "    except ValueError as e:\n"
    "        die(\"bad request spec: %s\" % e)\n"
    "    shape = spec.get(\"shape\")\n"
    "    if shape not in BUILDERS:\n"
    "        die(\"unknown shape: %s\" % shape)\n"
    "    try:\n"
    "        url, headers, body = BUILDERS[shape](spec)\n"
    "    except OSError as e:\n"
    "        die(\"cannot read an attachment: %s\" % e)\n"
    "    try:\n"
    "        resp = open_request(url, headers, body)\n"
    "    except urllib.error.HTTPError as e:\n"
    "        detail = e.read().decode(\"utf-8\", \"replace\")[:2000]\n"
    "        die(detail or e.reason, e.code)\n"
    "    except urllib.error.URLError as e:\n"
    "        die(\"cannot reach %s: %s\" % (url, e.reason), -1)\n"
    "    except OSError as e:\n"
    "        die(\"transport error: %s\" % e, -1)\n"
    "    if spec.get(\"stream\"):\n"
    "        run_stream(shape, resp)\n"
    "    else:\n"
    "        try:\n"
    "            obj = json.loads(resp.read().decode(\"utf-8\"))\n"
    "        except ValueError as e:\n"
    "            die(\"provider did not return JSON: %s\" % e)\n"
    "        r = READERS[shape](obj)\n"
    "        emit({\"t\": \"final\", \"text\": r[\"text\"], \"model\": r[\"model\"],\n"
    "              \"finish_reason\": r[\"finish_reason\"], \"usage\": r[\"usage\"]})\n"
    "\n"
    "\n"
    "if __name__ == \"__main__\":\n"
    "    main()\n"
    "\n"
    ;
